[theme]
primaryColor = "#d4a017"                # Golden amber for highlights, buttons, or key metrics
backgroundColor = "#0a1e3d"             # Midnight blue for a rich, deep background
secondaryBackgroundColor = "#1e3a6d"    # Slightly lighter blue for panels or sidebars
textColor = "#f5f5f5"                   # Off-white for high-contrast, readable text
font = "sans serif"                     # Clean and modern font